import { z } from 'zod';
import { nullishObject } from './utils';

const MoveItemSchema = nullishObject({
  item_id: z.any(),
  user_id: z.any(),
  parent_item_id: z.any(),
  category_id: z.any(),
  name: z.any(),
  identifier: z.any(),
  locale: z.any(),
  make_id: z.any(),
  make_name: z.any(),
  model_id: z.any(),
  model_name: z.any(),
  image_path: z.any(),
  width: z.any(),
  depth: z.any(),
  height: z.any(),
  weight: z.any(),
  original_width: z.any(),
  original_depth: z.any(),
  original_height: z.any(),
  original_weight: z.any(),
  dimension_unit: z.any(),
  weight_unit: z.any(),
  volume: z.any(),
  is_admin: z.any(),
  is_complete: z.any(),
  location_id: z.any(),
  loading_time: z.any(),
  fake_id: z.any(),
  quantity: z.any(),
}).optional();

const AddressDataSchema = nullishObject({
  ISO_3166_1_Alpha_2: z.any(),
  country: z.any(),
  latitude: z.any(),
  longitude: z.any(),
  lookup: z.any(),
  name: z.any(),
  phone_number: z.any(),
  postcode: z.any(),
  town: z.any(),
  region: z.any(),
}).optional();

const UserInfoSchema = nullishObject({
  email: z.any(),
  phone_number: z.any(),
  full_name: z.any(),
}).optional();

const CartItemSchema = nullishObject({
  service_id: z.any(),
  type: z.any(),
  base_price: z.any(),
  unit_price: z.any(),
  rate_price: z.any(),
  min_price: z.any(),
  excess: z.any(),
  excess_rate: z.any(),
  cover: z.any(),
  international_cover: z.any(),
  international_rate_price: z.any(),
  international_min_price: z.any(),
  international_excess: z.any(),
  international_excess_rate: z.any(),
  international_available: z.any(),
  limit: z.any(),
  inc_tax: z.any(),
  units: z.any(),
  tax_rate: z.any(),
  tax_type: z.any(),
  icon: z.any(),
  order: z.any(),
  name: z.any(),
  description: z.any(),
  visible_for_admin: z.any(),
  visible_for_customer: z.any(),
  visible_for_provider: z.any(),
  customer_can_add: z.any(),
  fee_numerator: z.any(),
  fee_denominator: z.any(),
  cutoff_time: z.any(),
  locale: z.any(),
  version: z.any(),
  basedOnValueOfGoods: z.any(),
  category_service_id: z.any(),
  category_id: z.any(),
  amount: z.any(),
  qty: z.any(),
}).optional();

const PaymentGatewayOptionSchema = nullishObject({
  default: z.any(),
  paymentAction: z.any(),
  isCheckoutDisabledInModal: z.any(),
  riskSettings: nullishObject({
    avs: z.boolean(),
    reasons: nullishObject({
      pickupInThreeDays: z.any(),
    })
      .or(z.array(z.any()))
      .optional(),
  }).optional(),
}).optional();

const AvailablePaymentGatewaysSchema = nullishObject({
  adyen_card: PaymentGatewayOptionSchema,
  adyen_web_sdk: PaymentGatewayOptionSchema,
  braintree: PaymentGatewayOptionSchema,
  credit: PaymentGatewayOptionSchema,
  checkout_card: PaymentGatewayOptionSchema,
  pgs_stripe: PaymentGatewayOptionSchema,
}).optional();

const LowestPriceSchema = nullishObject({
  standard: z.any(),
  premium: z.any(),
}).optional();

const PricesKeysSchema = nullishObject({
  admin: z.any(),
  standard: z.any(),
  standard_plus: z.any(),
  premium: z.any(),
  flexible: z.any(),
  options: z.any(),
  options_delivery: z.any(),
  customer: z.any(),
  provider: z.any(),
  routes: z.any(),
}).optional();

const ListingSchema = nullishObject({
  stage: z.any(),
  toStage: z.any(),
  v: z.any(),
  pickup_date: z.any(),
  admin_pickup_date: z.any(),
  admin_pickup_date_end: z.any(),
  admin_delivery_date: z.any(),
  admin_delivery_date_end: z.any(),
  category_id: z.any(),
  move_items: z.array(MoveItemSchema),
  pickup_address_data: AddressDataSchema,
  from: z.any(),
  delivery_address_data: AddressDataSchema,
  to: z.any(),
  user_info: UserInfoSchema,
  vehicle_is_operational: z.any(),
  origin_property_level: z.any(),
  destination_property_level: z.any(),
  prices: z.any(),
  pickup_time: z.any(),
  pickup_time_end: z.any(),
  men_required: z.any(),
  saverOption: z.any(),
  owner: z.any(),
  job_is_for_business: z.any(),
  landing_id: z.any(),
  price_option: z.any(),
  quotes_to: z.any(),
  selected_van: z.any(),
  hours_selected: z.any(),
  selectedTimeOption: z.any(),
  selectedTimeOptionType: z.any(),
  packageType: z.any(),
  pre_listing_id: z.any(),
  human_id: z.any(),
  listing_id: z.any(),
  pre_listing_url: z.any(),
  jump_to_stage: z.any(),
  categoryIdent: z.any(),
  has_ferry: z.any(),
  is_international: z.any(),
  is_in_congestion_zone: z.any(),
  classification_target: z.any(),
  is_instant_pricing: z.any(),
  delivery_date_option: z.any(),
  pickup_date_option: z.any(),
  delivery_date_end: z.any(),
  pickup_date_end: z.any(),
  delivery_date: z.any(),
  delivery_time_end: z.any(),
  delivery_time: z.any(),
  total_price: z.any(),
  force_jump_to: z.any(),
  men_option_available: z.array(z.any()),
  lowest_price: LowestPriceSchema,
  distance: z.any(),
  duration: z.any(),
  listing_cart: z.array(CartItemSchema),
  fields: z.any(),
  special_instruction: z.any(),
  ranged_offset_future: z.any(),
  ranged_offset_past: z.any(),
  refund_id: z.any(),
  is_featured: z.any(),
  listingVatPlan: z.any(),
  listingAvailablePaymentGateways: AvailablePaymentGatewaysSchema,
  route_summary: z.any(),
  rendered_route_summary: z.any(),
  route_locked: z.any(),
  rendered_distance: z.any(),
  could_be_setprice: z.any(),
  short_label: z.any(),
  date_mode: z.any(),
  lead_id: z.any(),
  vehicle_services: z.any(),
  vehicle_condition: z.any(),
  vehicle_worth: z.any(),
  vehicle_mobility: z.any(),
  volume_units: z.any(),
  overall_weight_units: z.any(),
  overall_weight: z.any(),
  volume: z.any(),
  number_pallets: z.any(),
  additional_items: z.any(),
  packing_service_required: z.any(),
  destination_parking: z.any(),
  destination_property_elevator: z.any(),
  destination_number_floors: z.any(),
  destination_type_of_property: z.any(),
  origin_parking: z.any(),
  origin_property_elevator: z.any(),
  origin_number_floors: z.any(),
  origin_type_of_property: z.any(),
  customer_category: z.any(),
  transport_method: z.any(),
  is_delivery_same_as_pickup: z.any(),
  dist_localised: z.any(),
  render_expires: z.any(),
  render_delivery_date: z.any(),
  render_pickup_date: z.any(),
  flag: z.any(),
  tp_label: z.any(),
  listing_history: z.any(),
  image_ids: z.array(z.any()),
  originalEstimatedPrice: z.any(),
  currency_symbol: z.any(),
  is_frozen: z.any(),
  is_search_restricted: z.any(),
  version: z.any(),
  locale: z.any(),
  seo_slug: z.any(),
  title_signature: z.any(),
  title: z.any(),
  seo_duplicate: z.any(),
  seo_value: z.any(),
  relisting: z.any(),
  last_modified: z.any(),
  max_bid: z.any(),
  fee_waived: z.any(),
  promo_code: z.any(),
  urgent: z.any(),
  recommended_by: z.any(),
  featured_invoice_id: z.any(),
  featured_payment_id: z.any(),
  provider_archived: z.any(),
  archived: z.any(),
  bid_accepted_at: z.any(),
  expire_warn: z.any(),
  ebay_active: z.any(),
  ebay_expires: z.any(),
  ebay_seller_id: z.any(),
  ebay_item_id: z.any(),
  customer_feedback_requested_at: z.any(),
  customer_feedback_created_at: z.any(),
  customer_feedback_comment: z.any(),
  customer_feedback_score: z.any(),
  feedback_prompted: z.any(),
  feedback_created_at: z.any(),
  feedback_comment: z.any(),
  feedback_score: z.any(),
  winning_bid_id: z.any(),
  chosen_provider: z.any(),
  direction: z.any(),
  expires: z.any(),
  completed_at: z.any(),
  activated_at: z.any(),
  created_at: z.string(),
  sms_updates: z.any(),
  status: z.any(),
  lowest_bidder: z.any(),
  lowest_bid: z.any(),
  bid_count: z.any(),
  currency_id: z.any(),
  delivery_range: z.any(),
  pickup_range: z.string(),
  delivery_flexible: z.any(),
  pickup_flexible: z.any(),
  delivery_date_mode: z.any(),
  pickup_date_mode: z.any(),
  delivery_address: z.any(),
  pickup_address: z.any(),
  signature_label: z.any(),
  label: z.any(),
  label_for_customer: z.any(),
  admin_label: z.any(),
  admin_label_for_customer: z.any(),
  route_id: z.any(),
  classification: z.any(),
  user_id: z.any(),
  storage: z.any(),
  admin_marked_as_storage: z.any(),
  contactless_move: z.any(),
  category_subset: z.any(),
  is_ads_storage_granted: z.any(),
  pas_amount: z.any(),
  pas_pct: z.any(),
  pre_pickup_date: z.any(),
  tax_identification_number: z.any(),
  admin_difficult_requirements: z.any(),
  calendarLabels: z.any(),
  edit_type: z.any(),
  hash: z.any(),
  is_london: z.any(),
  pricesKeys: PricesKeysSchema,
  availableWindow: z.any(),
  estimated_loading_time: z.any(),
  estimated_unloading_time: z.any(),
  exp_bookings: z.any(),
  exp_pick_up_location: z.any(),
  pre_listing_credit: z.any(),
  start_property_type: z.any(),
  start_property_bedrooms: z.any(),
  start_floor: z.any(),
  start_lift: z.any(),
  end_property_type: z.any(),
  end_property_bedrooms: z.any(),
  end_floor: z.any(),
  end_lift: z.any(),
  premium: z.any(),
  is_standard_plus: z.any(),
  special_instructions: z.any(),
  lifetime_discount: z.any(),
  adjustment_service_enabled: z.any(),
  homesense: z.any(),
  affiliate_attribution_option: z.any(),
  parent_id: z.any(),
  stage_max: z.any(),
  currency: z.any(),
  parentHash: z.any(),
  isConvertedFromFurnitureToHouseMove: z.any(),
});

export const PrelistingSchema = z.object({
  listing: ListingSchema,
});
